name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use the Python 3.9 container as the runner environment
    runs-on: ubuntu-latest
    container: python:3.9-slim 

    # Define the PostgreSQL service required for testing
    services:
      postgres:
        image: postgres:alpine
        # Map port 5432 in the container to port 5432 in the runner environment
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        # Options to wait until the database is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Use the latest stable version of checkout
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests
        env:
          # This variable links the application (running in the 'python:3.9-slim' container)
          # to the PostgreSQL service running next to it (aliased as 'postgres')
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
